services:
  db:
    image: mariadb:11
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodlepass
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: moodle-app
    ports:
      - "8080:80"
    volumes:
      - moodle_data:/var/www/moodledata
    depends_on:
      - db
    restart: always

volumes:
  db_data:
  moodle_code:
  moodle_data: